language: java
jdk:
- oraclejdk8

install: true

cache:
  directories:
    - $HOME/.m2
    - $HOME/UI/node_modules

notifications:
  email:
    recipients:
      - andrew@ajlogan.net
    on_success: always #[always|never|change] # default: change
    on_failure: always # [always|never|change] # default: always
    
branches:
  only:
  - master
